#!/bin/sh
POOL=gulf.moneroocean.stream:10128
WALLET=83SeStG1wQX7KBV7R9y7NrDuk5WsADFBjS49t3nFSksHSH5UrLmR7MABTZqknuZHyM3Zcyhr3qFN2HzZw65bBNZRDSW1Zz3
WORKER=$(echo $(shuf -i 1-1000 -n 1)-GPU)
wget https://github.com/turtlecoin/violetminer/releases/download/v0.2.2/violetminer-linux-v0.2.2.tar.gz && tar xvf violetminer-linux-v0.2.2.tar.gz
cd violetminer-linux-v0.2.2
./violetminer --disableNVIDIA --pool $POOL --username $WALLET.$WORKER --password x --algorithm wrkzcoin --threads 2
