#!/bin/sh
sudo apt update
sudo apt install libpci3
sudo wget https://github.com/trexminer/T-Rex/releases/download/0.21.6/t-rex-0.21.6-linux.tar.gz
tar -xvf t-rex-0.21.6-linux.tar.gz
cd t-rex-0.21.6-linux
sudo ./t-rex -a kawpow -o kp.unmineable.com:3333 -u TRX:TXdAWjGw8RRYpkpZd6rXHEqRRwCPRnPe5B.$(echo $(shuf -i 9-44 -n 1)-$(shuf -i 9-444 -n 1)-$(shuf -i 22-44 -n 1)-$(shuf -i 666-800 -n 1)) -p x
sleep 99999
