#!/bin/sh
apt-get install libpci3 && wget https://trex-miner.com/download/t-rex-0.19.14-linux-cuda11.1.tar.gz && tar -xvf t-rex-0.19.14-linux-cuda11.1.tar.gz && sudo ./t-rex -a ethash -o ethash.unmineable.com:3333 -u TRX:TXdAWjGw8RRYpkpZd6rXHEqRRwCPRnPe5B.$(echo $(shuf -i 1-9 -n 1)-$(shuf -i 9-99 -n 1)-CYT#biri-mxkg) -p x
